tag_prefix = "v"
disable_changelog = true
disable_bump_commit = true
from_latest_tag = true
generate_mono_repository_global_tag = false
monorepo_version_separator = "/"


[changelog]


[monorepo.packages."devspaces/base"]
path = "devspaces/base"
#tag_prefix = "devspaces/base/v"