ARG REGISTRY_REDHAT_IO=registry.redhat.io
ARG REGISTRY_ACCESS_REDHAT_COM=registry.access.redhat.com

FROM ${REGISTRY_ACCESS_REDHAT_COM}/hi/rust:latest AS crates
ARG GIT_DELTA_VERSION=0.19.2
ARG PREK_VERSION=0.4.13

RUN cargo install  \
    git-delta@${GIT_DELTA_VERSION}  \
    prek@${PREK_VERSION}

FROM ${REGISTRY_REDHAT_IO}/devspaces/udi-base-rhel10:3.29.1
USER 0

ARG BIN_DIR=/usr/local/bin
COPY --from=crates --chown=root:root --chmod=755 /usr/local/cargo/bin/* ${BIN_DIR}/

ARG EPEL_BASE_URL=https://dl.fedoraproject.org/pub/epel
RUN dnf copr enable -y atim/starship  \
    && dnf install -y "${EPEL_BASE_URL}/epel-release-latest-10.noarch.rpm"  \
    && dnf install -y --setopt=install_weak_deps=0  \
    zsh ripgrep starship

USER user
