ARG REGISTRY_REDHAT_IO=registry.redhat.io

FROM ${REGISTRY_REDHAT_IO}/devspaces/udi-base-rhel10:3.29.1
ARG EPEL_BASE_URL=https://dl.fedoraproject.org/pub/epel
USER 0

RUN dnf install -y "${EPEL_BASE_URL}/epel-release-latest-10.noarch.rpm" \
    && RUN dnf install -y zsh ripgrep
